package tw.com.elf.mapper.airset;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import tw.com.elf.model.airset.Air0客戶;
import tw.com.elf.model.airset.AirsetExample;

@Mapper
public interface Air0客戶Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    long countByExample(AirsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int deleteByExample(AirsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int deleteByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int insert(Air0客戶 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int insertSelective(Air0客戶 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    List<Air0客戶> selectByExample(AirsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    Air0客戶 selectByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int updateByExampleSelective(@Param("record") Air0客戶 record, @Param("example") AirsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int updateByExample(@Param("record") Air0客戶 record, @Param("example") AirsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int updateByPrimaryKeySelective(Air0客戶 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int updateByPrimaryKey(Air0客戶 record);
}