spring:
  datasource:
    airset:
      jdbc-url: jdbc:sqlserver://192.168.20.131:1433;databaseName=AIRSET;encrypt=true;trustServerCertificate=true
      username: sa
      password: Sql@admin
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    airshop:
      jdbc-url: jdbc:sqlserver://192.168.20.131:1433;databaseName=AIRSHOP;encrypt=true;trustServerCertificate=true
      username: sa
      password: Sql@admin
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis:
  type-aliases-package: tw.com.elf.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081