package tw.com.elf.model.airshop;

public class Categories {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORIES.CATEGORY_ID
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CATEGORIES.NAME
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORIES.CATEGORY_ID
     *
     * @return the value of CATEGORIES.CATEGORY_ID
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORIES.CATEGORY_ID
     *
     * @param categoryId the value for CATEGORIES.CATEGORY_ID
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CATEGORIES.NAME
     *
     * @return the value of CATEGORIES.NAME
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CATEGORIES.NAME
     *
     * @param name the value for CATEGORIES.NAME
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }
}