package tw.com.elf.model.airshop;

public class ProductImages {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_IMAGES.IMAGE_ID
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    private Integer imageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_IMAGES.PRODUCT_ID
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_IMAGES.IMAGE_URL
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    private String imageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT_IMAGES.SORT_ORDER
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    private Integer sortOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_IMAGES.IMAGE_ID
     *
     * @return the value of PRODUCT_IMAGES.IMAGE_ID
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public Integer getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_IMAGES.IMAGE_ID
     *
     * @param imageId the value for PRODUCT_IMAGES.IMAGE_ID
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public void setImageId(Integer imageId) {
        this.imageId = imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_IMAGES.PRODUCT_ID
     *
     * @return the value of PRODUCT_IMAGES.PRODUCT_ID
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_IMAGES.PRODUCT_ID
     *
     * @param productId the value for PRODUCT_IMAGES.PRODUCT_ID
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_IMAGES.IMAGE_URL
     *
     * @return the value of PRODUCT_IMAGES.IMAGE_URL
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_IMAGES.IMAGE_URL
     *
     * @param imageUrl the value for PRODUCT_IMAGES.IMAGE_URL
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT_IMAGES.SORT_ORDER
     *
     * @return the value of PRODUCT_IMAGES.SORT_ORDER
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT_IMAGES.SORT_ORDER
     *
     * @param sortOrder the value for PRODUCT_IMAGES.SORT_ORDER
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }
}