package tw.com.elf.model.airshop;

import java.math.BigDecimal;
import java.util.Date;

public class Products {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.PRODUCT_ID
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.NAME
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.DESCRIPTION
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.PRICE
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.DISCOUNT_PRICE
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private BigDecimal discountPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.RATING_AVG
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private BigDecimal ratingAvg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.REVIEW_COUNT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private Integer reviewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.STOCK_QUANTITY
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private Integer stockQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.CATEGORY_ID
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.BRAND_ID
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.CREATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.UPDATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.PURCHASE_COUNT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private Integer purchaseCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.IS_HOT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private Boolean isHot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCTS.IS_24HSHIPPING
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    private Boolean is24hshipping;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.PRODUCT_ID
     *
     * @return the value of PRODUCTS.PRODUCT_ID
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.PRODUCT_ID
     *
     * @param productId the value for PRODUCTS.PRODUCT_ID
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.NAME
     *
     * @return the value of PRODUCTS.NAME
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.NAME
     *
     * @param name the value for PRODUCTS.NAME
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.DESCRIPTION
     *
     * @return the value of PRODUCTS.DESCRIPTION
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.DESCRIPTION
     *
     * @param description the value for PRODUCTS.DESCRIPTION
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.PRICE
     *
     * @return the value of PRODUCTS.PRICE
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.PRICE
     *
     * @param price the value for PRODUCTS.PRICE
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.DISCOUNT_PRICE
     *
     * @return the value of PRODUCTS.DISCOUNT_PRICE
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.DISCOUNT_PRICE
     *
     * @param discountPrice the value for PRODUCTS.DISCOUNT_PRICE
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.RATING_AVG
     *
     * @return the value of PRODUCTS.RATING_AVG
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public BigDecimal getRatingAvg() {
        return ratingAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.RATING_AVG
     *
     * @param ratingAvg the value for PRODUCTS.RATING_AVG
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setRatingAvg(BigDecimal ratingAvg) {
        this.ratingAvg = ratingAvg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.REVIEW_COUNT
     *
     * @return the value of PRODUCTS.REVIEW_COUNT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public Integer getReviewCount() {
        return reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.REVIEW_COUNT
     *
     * @param reviewCount the value for PRODUCTS.REVIEW_COUNT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setReviewCount(Integer reviewCount) {
        this.reviewCount = reviewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.STOCK_QUANTITY
     *
     * @return the value of PRODUCTS.STOCK_QUANTITY
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public Integer getStockQuantity() {
        return stockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.STOCK_QUANTITY
     *
     * @param stockQuantity the value for PRODUCTS.STOCK_QUANTITY
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setStockQuantity(Integer stockQuantity) {
        this.stockQuantity = stockQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.CATEGORY_ID
     *
     * @return the value of PRODUCTS.CATEGORY_ID
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.CATEGORY_ID
     *
     * @param categoryId the value for PRODUCTS.CATEGORY_ID
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.BRAND_ID
     *
     * @return the value of PRODUCTS.BRAND_ID
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.BRAND_ID
     *
     * @param brandId the value for PRODUCTS.BRAND_ID
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.CREATED_AT
     *
     * @return the value of PRODUCTS.CREATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.CREATED_AT
     *
     * @param createdAt the value for PRODUCTS.CREATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.UPDATED_AT
     *
     * @return the value of PRODUCTS.UPDATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.UPDATED_AT
     *
     * @param updatedAt the value for PRODUCTS.UPDATED_AT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.PURCHASE_COUNT
     *
     * @return the value of PRODUCTS.PURCHASE_COUNT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public Integer getPurchaseCount() {
        return purchaseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.PURCHASE_COUNT
     *
     * @param purchaseCount the value for PRODUCTS.PURCHASE_COUNT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setPurchaseCount(Integer purchaseCount) {
        this.purchaseCount = purchaseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.IS_HOT
     *
     * @return the value of PRODUCTS.IS_HOT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public Boolean getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.IS_HOT
     *
     * @param isHot the value for PRODUCTS.IS_HOT
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCTS.IS_24HSHIPPING
     *
     * @return the value of PRODUCTS.IS_24HSHIPPING
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public Boolean getIs24hshipping() {
        return is24hshipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCTS.IS_24HSHIPPING
     *
     * @param is24hshipping the value for PRODUCTS.IS_24HSHIPPING
     *
     * @mbg.generated Fri Jul 18 14:35:45 CST 2025
     */
    public void setIs24hshipping(Boolean is24hshipping) {
        this.is24hshipping = is24hshipping;
    }
}