package tw.com.elf.model.airshop;

import java.util.Date;

public class Reviews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEWS.REVIEW_ID
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    private Integer reviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEWS.PRODUCT_ID
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEWS.USER_ID
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEWS.RATING
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    private Integer rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEWS.COMMENT
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEWS.CREATED_AT
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REVIEWS.NAME
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEWS.REVIEW_ID
     *
     * @return the value of REVIEWS.REVIEW_ID
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public Integer getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEWS.REVIEW_ID
     *
     * @param reviewId the value for REVIEWS.REVIEW_ID
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEWS.PRODUCT_ID
     *
     * @return the value of REVIEWS.PRODUCT_ID
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEWS.PRODUCT_ID
     *
     * @param productId the value for REVIEWS.PRODUCT_ID
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEWS.USER_ID
     *
     * @return the value of REVIEWS.USER_ID
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEWS.USER_ID
     *
     * @param userId the value for REVIEWS.USER_ID
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEWS.RATING
     *
     * @return the value of REVIEWS.RATING
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEWS.RATING
     *
     * @param rating the value for REVIEWS.RATING
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEWS.COMMENT
     *
     * @return the value of REVIEWS.COMMENT
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEWS.COMMENT
     *
     * @param comment the value for REVIEWS.COMMENT
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEWS.CREATED_AT
     *
     * @return the value of REVIEWS.CREATED_AT
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEWS.CREATED_AT
     *
     * @param createdAt the value for REVIEWS.CREATED_AT
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REVIEWS.NAME
     *
     * @return the value of REVIEWS.NAME
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REVIEWS.NAME
     *
     * @param name the value for REVIEWS.NAME
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    public void setName(String name) {
        this.name = name;
    }
}