package tw.com.elf.model.airset;

import java.util.Date;

public class Air0客戶 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.EMAIL
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 姓名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.性別
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 性別;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.身分證字號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 身分證字號;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.郵遞區號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 郵遞區號;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.縣市鄉鎮
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 縣市鄉鎮;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.地址
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 地址;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.聯絡電話
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 聯絡電話;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.手機
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 手機;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.支付寶帳號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 支付寶帳號;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.支付寶姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 支付寶姓名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.入會時間
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private Date 入會時間;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.密碼
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 密碼;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.公司名稱
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 公司名稱;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.統一編號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 統一編號;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.出生日期
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private Date 出生日期;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.認證
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private Boolean 認證;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.聯絡人
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 聯絡人;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.會員種類
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 會員種類;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.控制
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private Boolean 控制;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.密碼MD5
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 密碼md5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.英文姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 英文姓名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.英文地址
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 英文地址;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.入倉代號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 入倉代號;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.入倉名稱
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 入倉名稱;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.國家
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private Integer 國家;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.渠道
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 渠道;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.載具明碼
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 載具明碼;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.載具隱碼
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 載具隱碼;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.載具歸戶狀態
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 載具歸戶狀態;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.公司驗證
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private Integer 公司驗證;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.公司驗證時間
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private Date 公司驗證時間;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.驗證
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private Boolean 驗證;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.驗證時間
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private Date 驗證時間;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.驗證姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 驗證姓名;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.驗證資訊
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 驗證資訊;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.暱稱
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String 暱稱;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.ID
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AIR0客戶.鎖定
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    private Integer 鎖定;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.EMAIL
     *
     * @return the value of AIR0客戶.EMAIL
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.EMAIL
     *
     * @param email the value for AIR0客戶.EMAIL
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.姓名
     *
     * @return the value of AIR0客戶.姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get姓名() {
        return 姓名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.姓名
     *
     * @param 姓名 the value for AIR0客戶.姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set姓名(String 姓名) {
        this.姓名 = 姓名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.性別
     *
     * @return the value of AIR0客戶.性別
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get性別() {
        return 性別;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.性別
     *
     * @param 性別 the value for AIR0客戶.性別
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set性別(String 性別) {
        this.性別 = 性別;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.身分證字號
     *
     * @return the value of AIR0客戶.身分證字號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get身分證字號() {
        return 身分證字號;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.身分證字號
     *
     * @param 身分證字號 the value for AIR0客戶.身分證字號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set身分證字號(String 身分證字號) {
        this.身分證字號 = 身分證字號;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.郵遞區號
     *
     * @return the value of AIR0客戶.郵遞區號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get郵遞區號() {
        return 郵遞區號;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.郵遞區號
     *
     * @param 郵遞區號 the value for AIR0客戶.郵遞區號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set郵遞區號(String 郵遞區號) {
        this.郵遞區號 = 郵遞區號;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.縣市鄉鎮
     *
     * @return the value of AIR0客戶.縣市鄉鎮
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get縣市鄉鎮() {
        return 縣市鄉鎮;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.縣市鄉鎮
     *
     * @param 縣市鄉鎮 the value for AIR0客戶.縣市鄉鎮
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set縣市鄉鎮(String 縣市鄉鎮) {
        this.縣市鄉鎮 = 縣市鄉鎮;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.地址
     *
     * @return the value of AIR0客戶.地址
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get地址() {
        return 地址;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.地址
     *
     * @param 地址 the value for AIR0客戶.地址
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set地址(String 地址) {
        this.地址 = 地址;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.聯絡電話
     *
     * @return the value of AIR0客戶.聯絡電話
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get聯絡電話() {
        return 聯絡電話;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.聯絡電話
     *
     * @param 聯絡電話 the value for AIR0客戶.聯絡電話
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set聯絡電話(String 聯絡電話) {
        this.聯絡電話 = 聯絡電話;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.手機
     *
     * @return the value of AIR0客戶.手機
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get手機() {
        return 手機;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.手機
     *
     * @param 手機 the value for AIR0客戶.手機
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set手機(String 手機) {
        this.手機 = 手機;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.支付寶帳號
     *
     * @return the value of AIR0客戶.支付寶帳號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get支付寶帳號() {
        return 支付寶帳號;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.支付寶帳號
     *
     * @param 支付寶帳號 the value for AIR0客戶.支付寶帳號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set支付寶帳號(String 支付寶帳號) {
        this.支付寶帳號 = 支付寶帳號;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.支付寶姓名
     *
     * @return the value of AIR0客戶.支付寶姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get支付寶姓名() {
        return 支付寶姓名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.支付寶姓名
     *
     * @param 支付寶姓名 the value for AIR0客戶.支付寶姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set支付寶姓名(String 支付寶姓名) {
        this.支付寶姓名 = 支付寶姓名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.入會時間
     *
     * @return the value of AIR0客戶.入會時間
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Date get入會時間() {
        return 入會時間;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.入會時間
     *
     * @param 入會時間 the value for AIR0客戶.入會時間
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set入會時間(Date 入會時間) {
        this.入會時間 = 入會時間;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.密碼
     *
     * @return the value of AIR0客戶.密碼
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get密碼() {
        return 密碼;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.密碼
     *
     * @param 密碼 the value for AIR0客戶.密碼
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set密碼(String 密碼) {
        this.密碼 = 密碼;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.公司名稱
     *
     * @return the value of AIR0客戶.公司名稱
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get公司名稱() {
        return 公司名稱;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.公司名稱
     *
     * @param 公司名稱 the value for AIR0客戶.公司名稱
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set公司名稱(String 公司名稱) {
        this.公司名稱 = 公司名稱;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.統一編號
     *
     * @return the value of AIR0客戶.統一編號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get統一編號() {
        return 統一編號;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.統一編號
     *
     * @param 統一編號 the value for AIR0客戶.統一編號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set統一編號(String 統一編號) {
        this.統一編號 = 統一編號;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.出生日期
     *
     * @return the value of AIR0客戶.出生日期
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Date get出生日期() {
        return 出生日期;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.出生日期
     *
     * @param 出生日期 the value for AIR0客戶.出生日期
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set出生日期(Date 出生日期) {
        this.出生日期 = 出生日期;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.認證
     *
     * @return the value of AIR0客戶.認證
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Boolean get認證() {
        return 認證;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.認證
     *
     * @param 認證 the value for AIR0客戶.認證
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set認證(Boolean 認證) {
        this.認證 = 認證;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.聯絡人
     *
     * @return the value of AIR0客戶.聯絡人
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get聯絡人() {
        return 聯絡人;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.聯絡人
     *
     * @param 聯絡人 the value for AIR0客戶.聯絡人
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set聯絡人(String 聯絡人) {
        this.聯絡人 = 聯絡人;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.會員種類
     *
     * @return the value of AIR0客戶.會員種類
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get會員種類() {
        return 會員種類;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.會員種類
     *
     * @param 會員種類 the value for AIR0客戶.會員種類
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set會員種類(String 會員種類) {
        this.會員種類 = 會員種類;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.控制
     *
     * @return the value of AIR0客戶.控制
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Boolean get控制() {
        return 控制;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.控制
     *
     * @param 控制 the value for AIR0客戶.控制
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set控制(Boolean 控制) {
        this.控制 = 控制;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.密碼MD5
     *
     * @return the value of AIR0客戶.密碼MD5
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get密碼md5() {
        return 密碼md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.密碼MD5
     *
     * @param 密碼md5 the value for AIR0客戶.密碼MD5
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set密碼md5(String 密碼md5) {
        this.密碼md5 = 密碼md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.英文姓名
     *
     * @return the value of AIR0客戶.英文姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get英文姓名() {
        return 英文姓名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.英文姓名
     *
     * @param 英文姓名 the value for AIR0客戶.英文姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set英文姓名(String 英文姓名) {
        this.英文姓名 = 英文姓名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.英文地址
     *
     * @return the value of AIR0客戶.英文地址
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get英文地址() {
        return 英文地址;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.英文地址
     *
     * @param 英文地址 the value for AIR0客戶.英文地址
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set英文地址(String 英文地址) {
        this.英文地址 = 英文地址;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.入倉代號
     *
     * @return the value of AIR0客戶.入倉代號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get入倉代號() {
        return 入倉代號;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.入倉代號
     *
     * @param 入倉代號 the value for AIR0客戶.入倉代號
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set入倉代號(String 入倉代號) {
        this.入倉代號 = 入倉代號;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.入倉名稱
     *
     * @return the value of AIR0客戶.入倉名稱
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get入倉名稱() {
        return 入倉名稱;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.入倉名稱
     *
     * @param 入倉名稱 the value for AIR0客戶.入倉名稱
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set入倉名稱(String 入倉名稱) {
        this.入倉名稱 = 入倉名稱;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.國家
     *
     * @return the value of AIR0客戶.國家
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Integer get國家() {
        return 國家;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.國家
     *
     * @param 國家 the value for AIR0客戶.國家
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set國家(Integer 國家) {
        this.國家 = 國家;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.渠道
     *
     * @return the value of AIR0客戶.渠道
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get渠道() {
        return 渠道;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.渠道
     *
     * @param 渠道 the value for AIR0客戶.渠道
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set渠道(String 渠道) {
        this.渠道 = 渠道;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.載具明碼
     *
     * @return the value of AIR0客戶.載具明碼
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get載具明碼() {
        return 載具明碼;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.載具明碼
     *
     * @param 載具明碼 the value for AIR0客戶.載具明碼
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set載具明碼(String 載具明碼) {
        this.載具明碼 = 載具明碼;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.載具隱碼
     *
     * @return the value of AIR0客戶.載具隱碼
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get載具隱碼() {
        return 載具隱碼;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.載具隱碼
     *
     * @param 載具隱碼 the value for AIR0客戶.載具隱碼
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set載具隱碼(String 載具隱碼) {
        this.載具隱碼 = 載具隱碼;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.載具歸戶狀態
     *
     * @return the value of AIR0客戶.載具歸戶狀態
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get載具歸戶狀態() {
        return 載具歸戶狀態;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.載具歸戶狀態
     *
     * @param 載具歸戶狀態 the value for AIR0客戶.載具歸戶狀態
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set載具歸戶狀態(String 載具歸戶狀態) {
        this.載具歸戶狀態 = 載具歸戶狀態;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.公司驗證
     *
     * @return the value of AIR0客戶.公司驗證
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Integer get公司驗證() {
        return 公司驗證;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.公司驗證
     *
     * @param 公司驗證 the value for AIR0客戶.公司驗證
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set公司驗證(Integer 公司驗證) {
        this.公司驗證 = 公司驗證;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.公司驗證時間
     *
     * @return the value of AIR0客戶.公司驗證時間
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Date get公司驗證時間() {
        return 公司驗證時間;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.公司驗證時間
     *
     * @param 公司驗證時間 the value for AIR0客戶.公司驗證時間
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set公司驗證時間(Date 公司驗證時間) {
        this.公司驗證時間 = 公司驗證時間;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.驗證
     *
     * @return the value of AIR0客戶.驗證
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Boolean get驗證() {
        return 驗證;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.驗證
     *
     * @param 驗證 the value for AIR0客戶.驗證
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set驗證(Boolean 驗證) {
        this.驗證 = 驗證;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.驗證時間
     *
     * @return the value of AIR0客戶.驗證時間
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Date get驗證時間() {
        return 驗證時間;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.驗證時間
     *
     * @param 驗證時間 the value for AIR0客戶.驗證時間
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set驗證時間(Date 驗證時間) {
        this.驗證時間 = 驗證時間;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.驗證姓名
     *
     * @return the value of AIR0客戶.驗證姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get驗證姓名() {
        return 驗證姓名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.驗證姓名
     *
     * @param 驗證姓名 the value for AIR0客戶.驗證姓名
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set驗證姓名(String 驗證姓名) {
        this.驗證姓名 = 驗證姓名;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.驗證資訊
     *
     * @return the value of AIR0客戶.驗證資訊
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get驗證資訊() {
        return 驗證資訊;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.驗證資訊
     *
     * @param 驗證資訊 the value for AIR0客戶.驗證資訊
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set驗證資訊(String 驗證資訊) {
        this.驗證資訊 = 驗證資訊;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.暱稱
     *
     * @return the value of AIR0客戶.暱稱
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String get暱稱() {
        return 暱稱;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.暱稱
     *
     * @param 暱稱 the value for AIR0客戶.暱稱
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set暱稱(String 暱稱) {
        this.暱稱 = 暱稱;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.ID
     *
     * @return the value of AIR0客戶.ID
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.ID
     *
     * @param id the value for AIR0客戶.ID
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AIR0客戶.鎖定
     *
     * @return the value of AIR0客戶.鎖定
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Integer get鎖定() {
        return 鎖定;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AIR0客戶.鎖定
     *
     * @param 鎖定 the value for AIR0客戶.鎖定
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void set鎖定(Integer 鎖定) {
        this.鎖定 = 鎖定;
    }
}