package tw.com.elf.mapper.airshop;

import tw.com.elf.model.airshop.Products;

public interface ProductsMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTS
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTS
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    int insert(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTS
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    int insertSelective(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTS
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    Products selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTS
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    int updateByPrimaryKeySelective(Products record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCTS
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    int updateByPrimaryKey(Products record);
}