package tw.com.elf.mapper.airshop;

import tw.com.elf.model.airshop.ProductImages;

public interface ProductImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMAGES
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    int deleteByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMAGES
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    int insert(ProductImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMAGES
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    int insertSelective(ProductImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMAGES
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    ProductImages selectByPrimaryKey(Integer imageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMAGES
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    int updateByPrimaryKeySelective(ProductImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT_IMAGES
     *
     * @mbg.generated Thu Jul 17 14:45:52 CST 2025
     */
    int updateByPrimaryKey(ProductImages record);
}