package tw.com.elf.mapper.airshop;

import tw.com.elf.model.airshop.Reviews;

public interface ReviewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REVIEWS
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    int deleteByPrimaryKey(Integer reviewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REVIEWS
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    int insert(Reviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REVIEWS
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    int insertSelective(Reviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REVIEWS
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    Reviews selectByPrimaryKey(Integer reviewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REVIEWS
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    int updateByPrimaryKeySelective(Reviews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REVIEWS
     *
     * @mbg.generated Tue Jul 22 13:54:09 CST 2025
     */
    int updateByPrimaryKey(Reviews record);
}