package tw.com.elf.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import tw.com.elf.model.Airset;
import tw.com.elf.model.AirsetExample;

@Mapper
public interface AirsetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    long countByExample(AirsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int deleteByExample(AirsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int deleteByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int insert(Airset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int insertSelective(Airset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    List<Airset> selectByExample(AirsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    Airset selectByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int updateByExampleSelective(@Param("record") Airset record, @Param("example") AirsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int updateByExample(@Param("record") Airset record, @Param("example") AirsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int updateByPrimaryKeySelective(Airset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    int updateByPrimaryKey(Airset record);
}