package tw.com.elf.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AirsetExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public AirsetExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria and姓名IsNull() {
            addCriterion("姓名 is null");
            return (Criteria) this;
        }

        public Criteria and姓名IsNotNull() {
            addCriterion("姓名 is not null");
            return (Criteria) this;
        }

        public Criteria and姓名EqualTo(String value) {
            addCriterion("姓名 =", value, "姓名");
            return (Criteria) this;
        }

        public Criteria and姓名NotEqualTo(String value) {
            addCriterion("姓名 <>", value, "姓名");
            return (Criteria) this;
        }

        public Criteria and姓名GreaterThan(String value) {
            addCriterion("姓名 >", value, "姓名");
            return (Criteria) this;
        }

        public Criteria and姓名GreaterThanOrEqualTo(String value) {
            addCriterion("姓名 >=", value, "姓名");
            return (Criteria) this;
        }

        public Criteria and姓名LessThan(String value) {
            addCriterion("姓名 <", value, "姓名");
            return (Criteria) this;
        }

        public Criteria and姓名LessThanOrEqualTo(String value) {
            addCriterion("姓名 <=", value, "姓名");
            return (Criteria) this;
        }

        public Criteria and姓名Like(String value) {
            addCriterion("姓名 like", value, "姓名");
            return (Criteria) this;
        }

        public Criteria and姓名NotLike(String value) {
            addCriterion("姓名 not like", value, "姓名");
            return (Criteria) this;
        }

        public Criteria and姓名In(List<String> values) {
            addCriterion("姓名 in", values, "姓名");
            return (Criteria) this;
        }

        public Criteria and姓名NotIn(List<String> values) {
            addCriterion("姓名 not in", values, "姓名");
            return (Criteria) this;
        }

        public Criteria and姓名Between(String value1, String value2) {
            addCriterion("姓名 between", value1, value2, "姓名");
            return (Criteria) this;
        }

        public Criteria and姓名NotBetween(String value1, String value2) {
            addCriterion("姓名 not between", value1, value2, "姓名");
            return (Criteria) this;
        }

        public Criteria and性別IsNull() {
            addCriterion("性別 is null");
            return (Criteria) this;
        }

        public Criteria and性別IsNotNull() {
            addCriterion("性別 is not null");
            return (Criteria) this;
        }

        public Criteria and性別EqualTo(String value) {
            addCriterion("性別 =", value, "性別");
            return (Criteria) this;
        }

        public Criteria and性別NotEqualTo(String value) {
            addCriterion("性別 <>", value, "性別");
            return (Criteria) this;
        }

        public Criteria and性別GreaterThan(String value) {
            addCriterion("性別 >", value, "性別");
            return (Criteria) this;
        }

        public Criteria and性別GreaterThanOrEqualTo(String value) {
            addCriterion("性別 >=", value, "性別");
            return (Criteria) this;
        }

        public Criteria and性別LessThan(String value) {
            addCriterion("性別 <", value, "性別");
            return (Criteria) this;
        }

        public Criteria and性別LessThanOrEqualTo(String value) {
            addCriterion("性別 <=", value, "性別");
            return (Criteria) this;
        }

        public Criteria and性別Like(String value) {
            addCriterion("性別 like", value, "性別");
            return (Criteria) this;
        }

        public Criteria and性別NotLike(String value) {
            addCriterion("性別 not like", value, "性別");
            return (Criteria) this;
        }

        public Criteria and性別In(List<String> values) {
            addCriterion("性別 in", values, "性別");
            return (Criteria) this;
        }

        public Criteria and性別NotIn(List<String> values) {
            addCriterion("性別 not in", values, "性別");
            return (Criteria) this;
        }

        public Criteria and性別Between(String value1, String value2) {
            addCriterion("性別 between", value1, value2, "性別");
            return (Criteria) this;
        }

        public Criteria and性別NotBetween(String value1, String value2) {
            addCriterion("性別 not between", value1, value2, "性別");
            return (Criteria) this;
        }

        public Criteria and身分證字號IsNull() {
            addCriterion("身分證字號 is null");
            return (Criteria) this;
        }

        public Criteria and身分證字號IsNotNull() {
            addCriterion("身分證字號 is not null");
            return (Criteria) this;
        }

        public Criteria and身分證字號EqualTo(String value) {
            addCriterion("身分證字號 =", value, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and身分證字號NotEqualTo(String value) {
            addCriterion("身分證字號 <>", value, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and身分證字號GreaterThan(String value) {
            addCriterion("身分證字號 >", value, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and身分證字號GreaterThanOrEqualTo(String value) {
            addCriterion("身分證字號 >=", value, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and身分證字號LessThan(String value) {
            addCriterion("身分證字號 <", value, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and身分證字號LessThanOrEqualTo(String value) {
            addCriterion("身分證字號 <=", value, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and身分證字號Like(String value) {
            addCriterion("身分證字號 like", value, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and身分證字號NotLike(String value) {
            addCriterion("身分證字號 not like", value, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and身分證字號In(List<String> values) {
            addCriterion("身分證字號 in", values, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and身分證字號NotIn(List<String> values) {
            addCriterion("身分證字號 not in", values, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and身分證字號Between(String value1, String value2) {
            addCriterion("身分證字號 between", value1, value2, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and身分證字號NotBetween(String value1, String value2) {
            addCriterion("身分證字號 not between", value1, value2, "身分證字號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號IsNull() {
            addCriterion("郵遞區號 is null");
            return (Criteria) this;
        }

        public Criteria and郵遞區號IsNotNull() {
            addCriterion("郵遞區號 is not null");
            return (Criteria) this;
        }

        public Criteria and郵遞區號EqualTo(String value) {
            addCriterion("郵遞區號 =", value, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號NotEqualTo(String value) {
            addCriterion("郵遞區號 <>", value, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號GreaterThan(String value) {
            addCriterion("郵遞區號 >", value, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號GreaterThanOrEqualTo(String value) {
            addCriterion("郵遞區號 >=", value, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號LessThan(String value) {
            addCriterion("郵遞區號 <", value, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號LessThanOrEqualTo(String value) {
            addCriterion("郵遞區號 <=", value, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號Like(String value) {
            addCriterion("郵遞區號 like", value, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號NotLike(String value) {
            addCriterion("郵遞區號 not like", value, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號In(List<String> values) {
            addCriterion("郵遞區號 in", values, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號NotIn(List<String> values) {
            addCriterion("郵遞區號 not in", values, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號Between(String value1, String value2) {
            addCriterion("郵遞區號 between", value1, value2, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and郵遞區號NotBetween(String value1, String value2) {
            addCriterion("郵遞區號 not between", value1, value2, "郵遞區號");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮IsNull() {
            addCriterion("縣市鄉鎮 is null");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮IsNotNull() {
            addCriterion("縣市鄉鎮 is not null");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮EqualTo(String value) {
            addCriterion("縣市鄉鎮 =", value, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮NotEqualTo(String value) {
            addCriterion("縣市鄉鎮 <>", value, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮GreaterThan(String value) {
            addCriterion("縣市鄉鎮 >", value, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮GreaterThanOrEqualTo(String value) {
            addCriterion("縣市鄉鎮 >=", value, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮LessThan(String value) {
            addCriterion("縣市鄉鎮 <", value, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮LessThanOrEqualTo(String value) {
            addCriterion("縣市鄉鎮 <=", value, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮Like(String value) {
            addCriterion("縣市鄉鎮 like", value, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮NotLike(String value) {
            addCriterion("縣市鄉鎮 not like", value, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮In(List<String> values) {
            addCriterion("縣市鄉鎮 in", values, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮NotIn(List<String> values) {
            addCriterion("縣市鄉鎮 not in", values, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮Between(String value1, String value2) {
            addCriterion("縣市鄉鎮 between", value1, value2, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and縣市鄉鎮NotBetween(String value1, String value2) {
            addCriterion("縣市鄉鎮 not between", value1, value2, "縣市鄉鎮");
            return (Criteria) this;
        }

        public Criteria and地址IsNull() {
            addCriterion("地址 is null");
            return (Criteria) this;
        }

        public Criteria and地址IsNotNull() {
            addCriterion("地址 is not null");
            return (Criteria) this;
        }

        public Criteria and地址EqualTo(String value) {
            addCriterion("地址 =", value, "地址");
            return (Criteria) this;
        }

        public Criteria and地址NotEqualTo(String value) {
            addCriterion("地址 <>", value, "地址");
            return (Criteria) this;
        }

        public Criteria and地址GreaterThan(String value) {
            addCriterion("地址 >", value, "地址");
            return (Criteria) this;
        }

        public Criteria and地址GreaterThanOrEqualTo(String value) {
            addCriterion("地址 >=", value, "地址");
            return (Criteria) this;
        }

        public Criteria and地址LessThan(String value) {
            addCriterion("地址 <", value, "地址");
            return (Criteria) this;
        }

        public Criteria and地址LessThanOrEqualTo(String value) {
            addCriterion("地址 <=", value, "地址");
            return (Criteria) this;
        }

        public Criteria and地址Like(String value) {
            addCriterion("地址 like", value, "地址");
            return (Criteria) this;
        }

        public Criteria and地址NotLike(String value) {
            addCriterion("地址 not like", value, "地址");
            return (Criteria) this;
        }

        public Criteria and地址In(List<String> values) {
            addCriterion("地址 in", values, "地址");
            return (Criteria) this;
        }

        public Criteria and地址NotIn(List<String> values) {
            addCriterion("地址 not in", values, "地址");
            return (Criteria) this;
        }

        public Criteria and地址Between(String value1, String value2) {
            addCriterion("地址 between", value1, value2, "地址");
            return (Criteria) this;
        }

        public Criteria and地址NotBetween(String value1, String value2) {
            addCriterion("地址 not between", value1, value2, "地址");
            return (Criteria) this;
        }

        public Criteria and聯絡電話IsNull() {
            addCriterion("聯絡電話 is null");
            return (Criteria) this;
        }

        public Criteria and聯絡電話IsNotNull() {
            addCriterion("聯絡電話 is not null");
            return (Criteria) this;
        }

        public Criteria and聯絡電話EqualTo(String value) {
            addCriterion("聯絡電話 =", value, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and聯絡電話NotEqualTo(String value) {
            addCriterion("聯絡電話 <>", value, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and聯絡電話GreaterThan(String value) {
            addCriterion("聯絡電話 >", value, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and聯絡電話GreaterThanOrEqualTo(String value) {
            addCriterion("聯絡電話 >=", value, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and聯絡電話LessThan(String value) {
            addCriterion("聯絡電話 <", value, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and聯絡電話LessThanOrEqualTo(String value) {
            addCriterion("聯絡電話 <=", value, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and聯絡電話Like(String value) {
            addCriterion("聯絡電話 like", value, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and聯絡電話NotLike(String value) {
            addCriterion("聯絡電話 not like", value, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and聯絡電話In(List<String> values) {
            addCriterion("聯絡電話 in", values, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and聯絡電話NotIn(List<String> values) {
            addCriterion("聯絡電話 not in", values, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and聯絡電話Between(String value1, String value2) {
            addCriterion("聯絡電話 between", value1, value2, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and聯絡電話NotBetween(String value1, String value2) {
            addCriterion("聯絡電話 not between", value1, value2, "聯絡電話");
            return (Criteria) this;
        }

        public Criteria and手機IsNull() {
            addCriterion("手機 is null");
            return (Criteria) this;
        }

        public Criteria and手機IsNotNull() {
            addCriterion("手機 is not null");
            return (Criteria) this;
        }

        public Criteria and手機EqualTo(String value) {
            addCriterion("手機 =", value, "手機");
            return (Criteria) this;
        }

        public Criteria and手機NotEqualTo(String value) {
            addCriterion("手機 <>", value, "手機");
            return (Criteria) this;
        }

        public Criteria and手機GreaterThan(String value) {
            addCriterion("手機 >", value, "手機");
            return (Criteria) this;
        }

        public Criteria and手機GreaterThanOrEqualTo(String value) {
            addCriterion("手機 >=", value, "手機");
            return (Criteria) this;
        }

        public Criteria and手機LessThan(String value) {
            addCriterion("手機 <", value, "手機");
            return (Criteria) this;
        }

        public Criteria and手機LessThanOrEqualTo(String value) {
            addCriterion("手機 <=", value, "手機");
            return (Criteria) this;
        }

        public Criteria and手機Like(String value) {
            addCriterion("手機 like", value, "手機");
            return (Criteria) this;
        }

        public Criteria and手機NotLike(String value) {
            addCriterion("手機 not like", value, "手機");
            return (Criteria) this;
        }

        public Criteria and手機In(List<String> values) {
            addCriterion("手機 in", values, "手機");
            return (Criteria) this;
        }

        public Criteria and手機NotIn(List<String> values) {
            addCriterion("手機 not in", values, "手機");
            return (Criteria) this;
        }

        public Criteria and手機Between(String value1, String value2) {
            addCriterion("手機 between", value1, value2, "手機");
            return (Criteria) this;
        }

        public Criteria and手機NotBetween(String value1, String value2) {
            addCriterion("手機 not between", value1, value2, "手機");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號IsNull() {
            addCriterion("支付寶帳號 is null");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號IsNotNull() {
            addCriterion("支付寶帳號 is not null");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號EqualTo(String value) {
            addCriterion("支付寶帳號 =", value, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號NotEqualTo(String value) {
            addCriterion("支付寶帳號 <>", value, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號GreaterThan(String value) {
            addCriterion("支付寶帳號 >", value, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號GreaterThanOrEqualTo(String value) {
            addCriterion("支付寶帳號 >=", value, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號LessThan(String value) {
            addCriterion("支付寶帳號 <", value, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號LessThanOrEqualTo(String value) {
            addCriterion("支付寶帳號 <=", value, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號Like(String value) {
            addCriterion("支付寶帳號 like", value, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號NotLike(String value) {
            addCriterion("支付寶帳號 not like", value, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號In(List<String> values) {
            addCriterion("支付寶帳號 in", values, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號NotIn(List<String> values) {
            addCriterion("支付寶帳號 not in", values, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號Between(String value1, String value2) {
            addCriterion("支付寶帳號 between", value1, value2, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶帳號NotBetween(String value1, String value2) {
            addCriterion("支付寶帳號 not between", value1, value2, "支付寶帳號");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名IsNull() {
            addCriterion("支付寶姓名 is null");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名IsNotNull() {
            addCriterion("支付寶姓名 is not null");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名EqualTo(String value) {
            addCriterion("支付寶姓名 =", value, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名NotEqualTo(String value) {
            addCriterion("支付寶姓名 <>", value, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名GreaterThan(String value) {
            addCriterion("支付寶姓名 >", value, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名GreaterThanOrEqualTo(String value) {
            addCriterion("支付寶姓名 >=", value, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名LessThan(String value) {
            addCriterion("支付寶姓名 <", value, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名LessThanOrEqualTo(String value) {
            addCriterion("支付寶姓名 <=", value, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名Like(String value) {
            addCriterion("支付寶姓名 like", value, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名NotLike(String value) {
            addCriterion("支付寶姓名 not like", value, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名In(List<String> values) {
            addCriterion("支付寶姓名 in", values, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名NotIn(List<String> values) {
            addCriterion("支付寶姓名 not in", values, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名Between(String value1, String value2) {
            addCriterion("支付寶姓名 between", value1, value2, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and支付寶姓名NotBetween(String value1, String value2) {
            addCriterion("支付寶姓名 not between", value1, value2, "支付寶姓名");
            return (Criteria) this;
        }

        public Criteria and入會時間IsNull() {
            addCriterion("入會時間 is null");
            return (Criteria) this;
        }

        public Criteria and入會時間IsNotNull() {
            addCriterion("入會時間 is not null");
            return (Criteria) this;
        }

        public Criteria and入會時間EqualTo(Date value) {
            addCriterion("入會時間 =", value, "入會時間");
            return (Criteria) this;
        }

        public Criteria and入會時間NotEqualTo(Date value) {
            addCriterion("入會時間 <>", value, "入會時間");
            return (Criteria) this;
        }

        public Criteria and入會時間GreaterThan(Date value) {
            addCriterion("入會時間 >", value, "入會時間");
            return (Criteria) this;
        }

        public Criteria and入會時間GreaterThanOrEqualTo(Date value) {
            addCriterion("入會時間 >=", value, "入會時間");
            return (Criteria) this;
        }

        public Criteria and入會時間LessThan(Date value) {
            addCriterion("入會時間 <", value, "入會時間");
            return (Criteria) this;
        }

        public Criteria and入會時間LessThanOrEqualTo(Date value) {
            addCriterion("入會時間 <=", value, "入會時間");
            return (Criteria) this;
        }

        public Criteria and入會時間In(List<Date> values) {
            addCriterion("入會時間 in", values, "入會時間");
            return (Criteria) this;
        }

        public Criteria and入會時間NotIn(List<Date> values) {
            addCriterion("入會時間 not in", values, "入會時間");
            return (Criteria) this;
        }

        public Criteria and入會時間Between(Date value1, Date value2) {
            addCriterion("入會時間 between", value1, value2, "入會時間");
            return (Criteria) this;
        }

        public Criteria and入會時間NotBetween(Date value1, Date value2) {
            addCriterion("入會時間 not between", value1, value2, "入會時間");
            return (Criteria) this;
        }

        public Criteria and密碼IsNull() {
            addCriterion("密碼 is null");
            return (Criteria) this;
        }

        public Criteria and密碼IsNotNull() {
            addCriterion("密碼 is not null");
            return (Criteria) this;
        }

        public Criteria and密碼EqualTo(String value) {
            addCriterion("密碼 =", value, "密碼");
            return (Criteria) this;
        }

        public Criteria and密碼NotEqualTo(String value) {
            addCriterion("密碼 <>", value, "密碼");
            return (Criteria) this;
        }

        public Criteria and密碼GreaterThan(String value) {
            addCriterion("密碼 >", value, "密碼");
            return (Criteria) this;
        }

        public Criteria and密碼GreaterThanOrEqualTo(String value) {
            addCriterion("密碼 >=", value, "密碼");
            return (Criteria) this;
        }

        public Criteria and密碼LessThan(String value) {
            addCriterion("密碼 <", value, "密碼");
            return (Criteria) this;
        }

        public Criteria and密碼LessThanOrEqualTo(String value) {
            addCriterion("密碼 <=", value, "密碼");
            return (Criteria) this;
        }

        public Criteria and密碼Like(String value) {
            addCriterion("密碼 like", value, "密碼");
            return (Criteria) this;
        }

        public Criteria and密碼NotLike(String value) {
            addCriterion("密碼 not like", value, "密碼");
            return (Criteria) this;
        }

        public Criteria and密碼In(List<String> values) {
            addCriterion("密碼 in", values, "密碼");
            return (Criteria) this;
        }

        public Criteria and密碼NotIn(List<String> values) {
            addCriterion("密碼 not in", values, "密碼");
            return (Criteria) this;
        }

        public Criteria and密碼Between(String value1, String value2) {
            addCriterion("密碼 between", value1, value2, "密碼");
            return (Criteria) this;
        }

        public Criteria and密碼NotBetween(String value1, String value2) {
            addCriterion("密碼 not between", value1, value2, "密碼");
            return (Criteria) this;
        }

        public Criteria and公司名稱IsNull() {
            addCriterion("公司名稱 is null");
            return (Criteria) this;
        }

        public Criteria and公司名稱IsNotNull() {
            addCriterion("公司名稱 is not null");
            return (Criteria) this;
        }

        public Criteria and公司名稱EqualTo(String value) {
            addCriterion("公司名稱 =", value, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and公司名稱NotEqualTo(String value) {
            addCriterion("公司名稱 <>", value, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and公司名稱GreaterThan(String value) {
            addCriterion("公司名稱 >", value, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and公司名稱GreaterThanOrEqualTo(String value) {
            addCriterion("公司名稱 >=", value, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and公司名稱LessThan(String value) {
            addCriterion("公司名稱 <", value, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and公司名稱LessThanOrEqualTo(String value) {
            addCriterion("公司名稱 <=", value, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and公司名稱Like(String value) {
            addCriterion("公司名稱 like", value, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and公司名稱NotLike(String value) {
            addCriterion("公司名稱 not like", value, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and公司名稱In(List<String> values) {
            addCriterion("公司名稱 in", values, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and公司名稱NotIn(List<String> values) {
            addCriterion("公司名稱 not in", values, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and公司名稱Between(String value1, String value2) {
            addCriterion("公司名稱 between", value1, value2, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and公司名稱NotBetween(String value1, String value2) {
            addCriterion("公司名稱 not between", value1, value2, "公司名稱");
            return (Criteria) this;
        }

        public Criteria and統一編號IsNull() {
            addCriterion("統一編號 is null");
            return (Criteria) this;
        }

        public Criteria and統一編號IsNotNull() {
            addCriterion("統一編號 is not null");
            return (Criteria) this;
        }

        public Criteria and統一編號EqualTo(String value) {
            addCriterion("統一編號 =", value, "統一編號");
            return (Criteria) this;
        }

        public Criteria and統一編號NotEqualTo(String value) {
            addCriterion("統一編號 <>", value, "統一編號");
            return (Criteria) this;
        }

        public Criteria and統一編號GreaterThan(String value) {
            addCriterion("統一編號 >", value, "統一編號");
            return (Criteria) this;
        }

        public Criteria and統一編號GreaterThanOrEqualTo(String value) {
            addCriterion("統一編號 >=", value, "統一編號");
            return (Criteria) this;
        }

        public Criteria and統一編號LessThan(String value) {
            addCriterion("統一編號 <", value, "統一編號");
            return (Criteria) this;
        }

        public Criteria and統一編號LessThanOrEqualTo(String value) {
            addCriterion("統一編號 <=", value, "統一編號");
            return (Criteria) this;
        }

        public Criteria and統一編號Like(String value) {
            addCriterion("統一編號 like", value, "統一編號");
            return (Criteria) this;
        }

        public Criteria and統一編號NotLike(String value) {
            addCriterion("統一編號 not like", value, "統一編號");
            return (Criteria) this;
        }

        public Criteria and統一編號In(List<String> values) {
            addCriterion("統一編號 in", values, "統一編號");
            return (Criteria) this;
        }

        public Criteria and統一編號NotIn(List<String> values) {
            addCriterion("統一編號 not in", values, "統一編號");
            return (Criteria) this;
        }

        public Criteria and統一編號Between(String value1, String value2) {
            addCriterion("統一編號 between", value1, value2, "統一編號");
            return (Criteria) this;
        }

        public Criteria and統一編號NotBetween(String value1, String value2) {
            addCriterion("統一編號 not between", value1, value2, "統一編號");
            return (Criteria) this;
        }

        public Criteria and出生日期IsNull() {
            addCriterion("出生日期 is null");
            return (Criteria) this;
        }

        public Criteria and出生日期IsNotNull() {
            addCriterion("出生日期 is not null");
            return (Criteria) this;
        }

        public Criteria and出生日期EqualTo(Date value) {
            addCriterion("出生日期 =", value, "出生日期");
            return (Criteria) this;
        }

        public Criteria and出生日期NotEqualTo(Date value) {
            addCriterion("出生日期 <>", value, "出生日期");
            return (Criteria) this;
        }

        public Criteria and出生日期GreaterThan(Date value) {
            addCriterion("出生日期 >", value, "出生日期");
            return (Criteria) this;
        }

        public Criteria and出生日期GreaterThanOrEqualTo(Date value) {
            addCriterion("出生日期 >=", value, "出生日期");
            return (Criteria) this;
        }

        public Criteria and出生日期LessThan(Date value) {
            addCriterion("出生日期 <", value, "出生日期");
            return (Criteria) this;
        }

        public Criteria and出生日期LessThanOrEqualTo(Date value) {
            addCriterion("出生日期 <=", value, "出生日期");
            return (Criteria) this;
        }

        public Criteria and出生日期In(List<Date> values) {
            addCriterion("出生日期 in", values, "出生日期");
            return (Criteria) this;
        }

        public Criteria and出生日期NotIn(List<Date> values) {
            addCriterion("出生日期 not in", values, "出生日期");
            return (Criteria) this;
        }

        public Criteria and出生日期Between(Date value1, Date value2) {
            addCriterion("出生日期 between", value1, value2, "出生日期");
            return (Criteria) this;
        }

        public Criteria and出生日期NotBetween(Date value1, Date value2) {
            addCriterion("出生日期 not between", value1, value2, "出生日期");
            return (Criteria) this;
        }

        public Criteria and認證IsNull() {
            addCriterion("認證 is null");
            return (Criteria) this;
        }

        public Criteria and認證IsNotNull() {
            addCriterion("認證 is not null");
            return (Criteria) this;
        }

        public Criteria and認證EqualTo(Boolean value) {
            addCriterion("認證 =", value, "認證");
            return (Criteria) this;
        }

        public Criteria and認證NotEqualTo(Boolean value) {
            addCriterion("認證 <>", value, "認證");
            return (Criteria) this;
        }

        public Criteria and認證GreaterThan(Boolean value) {
            addCriterion("認證 >", value, "認證");
            return (Criteria) this;
        }

        public Criteria and認證GreaterThanOrEqualTo(Boolean value) {
            addCriterion("認證 >=", value, "認證");
            return (Criteria) this;
        }

        public Criteria and認證LessThan(Boolean value) {
            addCriterion("認證 <", value, "認證");
            return (Criteria) this;
        }

        public Criteria and認證LessThanOrEqualTo(Boolean value) {
            addCriterion("認證 <=", value, "認證");
            return (Criteria) this;
        }

        public Criteria and認證In(List<Boolean> values) {
            addCriterion("認證 in", values, "認證");
            return (Criteria) this;
        }

        public Criteria and認證NotIn(List<Boolean> values) {
            addCriterion("認證 not in", values, "認證");
            return (Criteria) this;
        }

        public Criteria and認證Between(Boolean value1, Boolean value2) {
            addCriterion("認證 between", value1, value2, "認證");
            return (Criteria) this;
        }

        public Criteria and認證NotBetween(Boolean value1, Boolean value2) {
            addCriterion("認證 not between", value1, value2, "認證");
            return (Criteria) this;
        }

        public Criteria and聯絡人IsNull() {
            addCriterion("聯絡人 is null");
            return (Criteria) this;
        }

        public Criteria and聯絡人IsNotNull() {
            addCriterion("聯絡人 is not null");
            return (Criteria) this;
        }

        public Criteria and聯絡人EqualTo(String value) {
            addCriterion("聯絡人 =", value, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and聯絡人NotEqualTo(String value) {
            addCriterion("聯絡人 <>", value, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and聯絡人GreaterThan(String value) {
            addCriterion("聯絡人 >", value, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and聯絡人GreaterThanOrEqualTo(String value) {
            addCriterion("聯絡人 >=", value, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and聯絡人LessThan(String value) {
            addCriterion("聯絡人 <", value, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and聯絡人LessThanOrEqualTo(String value) {
            addCriterion("聯絡人 <=", value, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and聯絡人Like(String value) {
            addCriterion("聯絡人 like", value, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and聯絡人NotLike(String value) {
            addCriterion("聯絡人 not like", value, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and聯絡人In(List<String> values) {
            addCriterion("聯絡人 in", values, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and聯絡人NotIn(List<String> values) {
            addCriterion("聯絡人 not in", values, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and聯絡人Between(String value1, String value2) {
            addCriterion("聯絡人 between", value1, value2, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and聯絡人NotBetween(String value1, String value2) {
            addCriterion("聯絡人 not between", value1, value2, "聯絡人");
            return (Criteria) this;
        }

        public Criteria and會員種類IsNull() {
            addCriterion("會員種類 is null");
            return (Criteria) this;
        }

        public Criteria and會員種類IsNotNull() {
            addCriterion("會員種類 is not null");
            return (Criteria) this;
        }

        public Criteria and會員種類EqualTo(String value) {
            addCriterion("會員種類 =", value, "會員種類");
            return (Criteria) this;
        }

        public Criteria and會員種類NotEqualTo(String value) {
            addCriterion("會員種類 <>", value, "會員種類");
            return (Criteria) this;
        }

        public Criteria and會員種類GreaterThan(String value) {
            addCriterion("會員種類 >", value, "會員種類");
            return (Criteria) this;
        }

        public Criteria and會員種類GreaterThanOrEqualTo(String value) {
            addCriterion("會員種類 >=", value, "會員種類");
            return (Criteria) this;
        }

        public Criteria and會員種類LessThan(String value) {
            addCriterion("會員種類 <", value, "會員種類");
            return (Criteria) this;
        }

        public Criteria and會員種類LessThanOrEqualTo(String value) {
            addCriterion("會員種類 <=", value, "會員種類");
            return (Criteria) this;
        }

        public Criteria and會員種類Like(String value) {
            addCriterion("會員種類 like", value, "會員種類");
            return (Criteria) this;
        }

        public Criteria and會員種類NotLike(String value) {
            addCriterion("會員種類 not like", value, "會員種類");
            return (Criteria) this;
        }

        public Criteria and會員種類In(List<String> values) {
            addCriterion("會員種類 in", values, "會員種類");
            return (Criteria) this;
        }

        public Criteria and會員種類NotIn(List<String> values) {
            addCriterion("會員種類 not in", values, "會員種類");
            return (Criteria) this;
        }

        public Criteria and會員種類Between(String value1, String value2) {
            addCriterion("會員種類 between", value1, value2, "會員種類");
            return (Criteria) this;
        }

        public Criteria and會員種類NotBetween(String value1, String value2) {
            addCriterion("會員種類 not between", value1, value2, "會員種類");
            return (Criteria) this;
        }

        public Criteria and控制IsNull() {
            addCriterion("控制 is null");
            return (Criteria) this;
        }

        public Criteria and控制IsNotNull() {
            addCriterion("控制 is not null");
            return (Criteria) this;
        }

        public Criteria and控制EqualTo(Boolean value) {
            addCriterion("控制 =", value, "控制");
            return (Criteria) this;
        }

        public Criteria and控制NotEqualTo(Boolean value) {
            addCriterion("控制 <>", value, "控制");
            return (Criteria) this;
        }

        public Criteria and控制GreaterThan(Boolean value) {
            addCriterion("控制 >", value, "控制");
            return (Criteria) this;
        }

        public Criteria and控制GreaterThanOrEqualTo(Boolean value) {
            addCriterion("控制 >=", value, "控制");
            return (Criteria) this;
        }

        public Criteria and控制LessThan(Boolean value) {
            addCriterion("控制 <", value, "控制");
            return (Criteria) this;
        }

        public Criteria and控制LessThanOrEqualTo(Boolean value) {
            addCriterion("控制 <=", value, "控制");
            return (Criteria) this;
        }

        public Criteria and控制In(List<Boolean> values) {
            addCriterion("控制 in", values, "控制");
            return (Criteria) this;
        }

        public Criteria and控制NotIn(List<Boolean> values) {
            addCriterion("控制 not in", values, "控制");
            return (Criteria) this;
        }

        public Criteria and控制Between(Boolean value1, Boolean value2) {
            addCriterion("控制 between", value1, value2, "控制");
            return (Criteria) this;
        }

        public Criteria and控制NotBetween(Boolean value1, Boolean value2) {
            addCriterion("控制 not between", value1, value2, "控制");
            return (Criteria) this;
        }

        public Criteria and密碼md5IsNull() {
            addCriterion("密碼MD5 is null");
            return (Criteria) this;
        }

        public Criteria and密碼md5IsNotNull() {
            addCriterion("密碼MD5 is not null");
            return (Criteria) this;
        }

        public Criteria and密碼md5EqualTo(String value) {
            addCriterion("密碼MD5 =", value, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and密碼md5NotEqualTo(String value) {
            addCriterion("密碼MD5 <>", value, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and密碼md5GreaterThan(String value) {
            addCriterion("密碼MD5 >", value, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and密碼md5GreaterThanOrEqualTo(String value) {
            addCriterion("密碼MD5 >=", value, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and密碼md5LessThan(String value) {
            addCriterion("密碼MD5 <", value, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and密碼md5LessThanOrEqualTo(String value) {
            addCriterion("密碼MD5 <=", value, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and密碼md5Like(String value) {
            addCriterion("密碼MD5 like", value, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and密碼md5NotLike(String value) {
            addCriterion("密碼MD5 not like", value, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and密碼md5In(List<String> values) {
            addCriterion("密碼MD5 in", values, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and密碼md5NotIn(List<String> values) {
            addCriterion("密碼MD5 not in", values, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and密碼md5Between(String value1, String value2) {
            addCriterion("密碼MD5 between", value1, value2, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and密碼md5NotBetween(String value1, String value2) {
            addCriterion("密碼MD5 not between", value1, value2, "密碼md5");
            return (Criteria) this;
        }

        public Criteria and英文姓名IsNull() {
            addCriterion("英文姓名 is null");
            return (Criteria) this;
        }

        public Criteria and英文姓名IsNotNull() {
            addCriterion("英文姓名 is not null");
            return (Criteria) this;
        }

        public Criteria and英文姓名EqualTo(String value) {
            addCriterion("英文姓名 =", value, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文姓名NotEqualTo(String value) {
            addCriterion("英文姓名 <>", value, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文姓名GreaterThan(String value) {
            addCriterion("英文姓名 >", value, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文姓名GreaterThanOrEqualTo(String value) {
            addCriterion("英文姓名 >=", value, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文姓名LessThan(String value) {
            addCriterion("英文姓名 <", value, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文姓名LessThanOrEqualTo(String value) {
            addCriterion("英文姓名 <=", value, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文姓名Like(String value) {
            addCriterion("英文姓名 like", value, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文姓名NotLike(String value) {
            addCriterion("英文姓名 not like", value, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文姓名In(List<String> values) {
            addCriterion("英文姓名 in", values, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文姓名NotIn(List<String> values) {
            addCriterion("英文姓名 not in", values, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文姓名Between(String value1, String value2) {
            addCriterion("英文姓名 between", value1, value2, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文姓名NotBetween(String value1, String value2) {
            addCriterion("英文姓名 not between", value1, value2, "英文姓名");
            return (Criteria) this;
        }

        public Criteria and英文地址IsNull() {
            addCriterion("英文地址 is null");
            return (Criteria) this;
        }

        public Criteria and英文地址IsNotNull() {
            addCriterion("英文地址 is not null");
            return (Criteria) this;
        }

        public Criteria and英文地址EqualTo(String value) {
            addCriterion("英文地址 =", value, "英文地址");
            return (Criteria) this;
        }

        public Criteria and英文地址NotEqualTo(String value) {
            addCriterion("英文地址 <>", value, "英文地址");
            return (Criteria) this;
        }

        public Criteria and英文地址GreaterThan(String value) {
            addCriterion("英文地址 >", value, "英文地址");
            return (Criteria) this;
        }

        public Criteria and英文地址GreaterThanOrEqualTo(String value) {
            addCriterion("英文地址 >=", value, "英文地址");
            return (Criteria) this;
        }

        public Criteria and英文地址LessThan(String value) {
            addCriterion("英文地址 <", value, "英文地址");
            return (Criteria) this;
        }

        public Criteria and英文地址LessThanOrEqualTo(String value) {
            addCriterion("英文地址 <=", value, "英文地址");
            return (Criteria) this;
        }

        public Criteria and英文地址Like(String value) {
            addCriterion("英文地址 like", value, "英文地址");
            return (Criteria) this;
        }

        public Criteria and英文地址NotLike(String value) {
            addCriterion("英文地址 not like", value, "英文地址");
            return (Criteria) this;
        }

        public Criteria and英文地址In(List<String> values) {
            addCriterion("英文地址 in", values, "英文地址");
            return (Criteria) this;
        }

        public Criteria and英文地址NotIn(List<String> values) {
            addCriterion("英文地址 not in", values, "英文地址");
            return (Criteria) this;
        }

        public Criteria and英文地址Between(String value1, String value2) {
            addCriterion("英文地址 between", value1, value2, "英文地址");
            return (Criteria) this;
        }

        public Criteria and英文地址NotBetween(String value1, String value2) {
            addCriterion("英文地址 not between", value1, value2, "英文地址");
            return (Criteria) this;
        }

        public Criteria and入倉代號IsNull() {
            addCriterion("入倉代號 is null");
            return (Criteria) this;
        }

        public Criteria and入倉代號IsNotNull() {
            addCriterion("入倉代號 is not null");
            return (Criteria) this;
        }

        public Criteria and入倉代號EqualTo(String value) {
            addCriterion("入倉代號 =", value, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉代號NotEqualTo(String value) {
            addCriterion("入倉代號 <>", value, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉代號GreaterThan(String value) {
            addCriterion("入倉代號 >", value, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉代號GreaterThanOrEqualTo(String value) {
            addCriterion("入倉代號 >=", value, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉代號LessThan(String value) {
            addCriterion("入倉代號 <", value, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉代號LessThanOrEqualTo(String value) {
            addCriterion("入倉代號 <=", value, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉代號Like(String value) {
            addCriterion("入倉代號 like", value, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉代號NotLike(String value) {
            addCriterion("入倉代號 not like", value, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉代號In(List<String> values) {
            addCriterion("入倉代號 in", values, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉代號NotIn(List<String> values) {
            addCriterion("入倉代號 not in", values, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉代號Between(String value1, String value2) {
            addCriterion("入倉代號 between", value1, value2, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉代號NotBetween(String value1, String value2) {
            addCriterion("入倉代號 not between", value1, value2, "入倉代號");
            return (Criteria) this;
        }

        public Criteria and入倉名稱IsNull() {
            addCriterion("入倉名稱 is null");
            return (Criteria) this;
        }

        public Criteria and入倉名稱IsNotNull() {
            addCriterion("入倉名稱 is not null");
            return (Criteria) this;
        }

        public Criteria and入倉名稱EqualTo(String value) {
            addCriterion("入倉名稱 =", value, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and入倉名稱NotEqualTo(String value) {
            addCriterion("入倉名稱 <>", value, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and入倉名稱GreaterThan(String value) {
            addCriterion("入倉名稱 >", value, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and入倉名稱GreaterThanOrEqualTo(String value) {
            addCriterion("入倉名稱 >=", value, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and入倉名稱LessThan(String value) {
            addCriterion("入倉名稱 <", value, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and入倉名稱LessThanOrEqualTo(String value) {
            addCriterion("入倉名稱 <=", value, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and入倉名稱Like(String value) {
            addCriterion("入倉名稱 like", value, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and入倉名稱NotLike(String value) {
            addCriterion("入倉名稱 not like", value, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and入倉名稱In(List<String> values) {
            addCriterion("入倉名稱 in", values, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and入倉名稱NotIn(List<String> values) {
            addCriterion("入倉名稱 not in", values, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and入倉名稱Between(String value1, String value2) {
            addCriterion("入倉名稱 between", value1, value2, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and入倉名稱NotBetween(String value1, String value2) {
            addCriterion("入倉名稱 not between", value1, value2, "入倉名稱");
            return (Criteria) this;
        }

        public Criteria and國家IsNull() {
            addCriterion("國家 is null");
            return (Criteria) this;
        }

        public Criteria and國家IsNotNull() {
            addCriterion("國家 is not null");
            return (Criteria) this;
        }

        public Criteria and國家EqualTo(Integer value) {
            addCriterion("國家 =", value, "國家");
            return (Criteria) this;
        }

        public Criteria and國家NotEqualTo(Integer value) {
            addCriterion("國家 <>", value, "國家");
            return (Criteria) this;
        }

        public Criteria and國家GreaterThan(Integer value) {
            addCriterion("國家 >", value, "國家");
            return (Criteria) this;
        }

        public Criteria and國家GreaterThanOrEqualTo(Integer value) {
            addCriterion("國家 >=", value, "國家");
            return (Criteria) this;
        }

        public Criteria and國家LessThan(Integer value) {
            addCriterion("國家 <", value, "國家");
            return (Criteria) this;
        }

        public Criteria and國家LessThanOrEqualTo(Integer value) {
            addCriterion("國家 <=", value, "國家");
            return (Criteria) this;
        }

        public Criteria and國家In(List<Integer> values) {
            addCriterion("國家 in", values, "國家");
            return (Criteria) this;
        }

        public Criteria and國家NotIn(List<Integer> values) {
            addCriterion("國家 not in", values, "國家");
            return (Criteria) this;
        }

        public Criteria and國家Between(Integer value1, Integer value2) {
            addCriterion("國家 between", value1, value2, "國家");
            return (Criteria) this;
        }

        public Criteria and國家NotBetween(Integer value1, Integer value2) {
            addCriterion("國家 not between", value1, value2, "國家");
            return (Criteria) this;
        }

        public Criteria and渠道IsNull() {
            addCriterion("渠道 is null");
            return (Criteria) this;
        }

        public Criteria and渠道IsNotNull() {
            addCriterion("渠道 is not null");
            return (Criteria) this;
        }

        public Criteria and渠道EqualTo(String value) {
            addCriterion("渠道 =", value, "渠道");
            return (Criteria) this;
        }

        public Criteria and渠道NotEqualTo(String value) {
            addCriterion("渠道 <>", value, "渠道");
            return (Criteria) this;
        }

        public Criteria and渠道GreaterThan(String value) {
            addCriterion("渠道 >", value, "渠道");
            return (Criteria) this;
        }

        public Criteria and渠道GreaterThanOrEqualTo(String value) {
            addCriterion("渠道 >=", value, "渠道");
            return (Criteria) this;
        }

        public Criteria and渠道LessThan(String value) {
            addCriterion("渠道 <", value, "渠道");
            return (Criteria) this;
        }

        public Criteria and渠道LessThanOrEqualTo(String value) {
            addCriterion("渠道 <=", value, "渠道");
            return (Criteria) this;
        }

        public Criteria and渠道Like(String value) {
            addCriterion("渠道 like", value, "渠道");
            return (Criteria) this;
        }

        public Criteria and渠道NotLike(String value) {
            addCriterion("渠道 not like", value, "渠道");
            return (Criteria) this;
        }

        public Criteria and渠道In(List<String> values) {
            addCriterion("渠道 in", values, "渠道");
            return (Criteria) this;
        }

        public Criteria and渠道NotIn(List<String> values) {
            addCriterion("渠道 not in", values, "渠道");
            return (Criteria) this;
        }

        public Criteria and渠道Between(String value1, String value2) {
            addCriterion("渠道 between", value1, value2, "渠道");
            return (Criteria) this;
        }

        public Criteria and渠道NotBetween(String value1, String value2) {
            addCriterion("渠道 not between", value1, value2, "渠道");
            return (Criteria) this;
        }

        public Criteria and載具明碼IsNull() {
            addCriterion("載具明碼 is null");
            return (Criteria) this;
        }

        public Criteria and載具明碼IsNotNull() {
            addCriterion("載具明碼 is not null");
            return (Criteria) this;
        }

        public Criteria and載具明碼EqualTo(String value) {
            addCriterion("載具明碼 =", value, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具明碼NotEqualTo(String value) {
            addCriterion("載具明碼 <>", value, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具明碼GreaterThan(String value) {
            addCriterion("載具明碼 >", value, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具明碼GreaterThanOrEqualTo(String value) {
            addCriterion("載具明碼 >=", value, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具明碼LessThan(String value) {
            addCriterion("載具明碼 <", value, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具明碼LessThanOrEqualTo(String value) {
            addCriterion("載具明碼 <=", value, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具明碼Like(String value) {
            addCriterion("載具明碼 like", value, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具明碼NotLike(String value) {
            addCriterion("載具明碼 not like", value, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具明碼In(List<String> values) {
            addCriterion("載具明碼 in", values, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具明碼NotIn(List<String> values) {
            addCriterion("載具明碼 not in", values, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具明碼Between(String value1, String value2) {
            addCriterion("載具明碼 between", value1, value2, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具明碼NotBetween(String value1, String value2) {
            addCriterion("載具明碼 not between", value1, value2, "載具明碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼IsNull() {
            addCriterion("載具隱碼 is null");
            return (Criteria) this;
        }

        public Criteria and載具隱碼IsNotNull() {
            addCriterion("載具隱碼 is not null");
            return (Criteria) this;
        }

        public Criteria and載具隱碼EqualTo(String value) {
            addCriterion("載具隱碼 =", value, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼NotEqualTo(String value) {
            addCriterion("載具隱碼 <>", value, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼GreaterThan(String value) {
            addCriterion("載具隱碼 >", value, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼GreaterThanOrEqualTo(String value) {
            addCriterion("載具隱碼 >=", value, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼LessThan(String value) {
            addCriterion("載具隱碼 <", value, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼LessThanOrEqualTo(String value) {
            addCriterion("載具隱碼 <=", value, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼Like(String value) {
            addCriterion("載具隱碼 like", value, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼NotLike(String value) {
            addCriterion("載具隱碼 not like", value, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼In(List<String> values) {
            addCriterion("載具隱碼 in", values, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼NotIn(List<String> values) {
            addCriterion("載具隱碼 not in", values, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼Between(String value1, String value2) {
            addCriterion("載具隱碼 between", value1, value2, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具隱碼NotBetween(String value1, String value2) {
            addCriterion("載具隱碼 not between", value1, value2, "載具隱碼");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態IsNull() {
            addCriterion("載具歸戶狀態 is null");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態IsNotNull() {
            addCriterion("載具歸戶狀態 is not null");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態EqualTo(String value) {
            addCriterion("載具歸戶狀態 =", value, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態NotEqualTo(String value) {
            addCriterion("載具歸戶狀態 <>", value, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態GreaterThan(String value) {
            addCriterion("載具歸戶狀態 >", value, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態GreaterThanOrEqualTo(String value) {
            addCriterion("載具歸戶狀態 >=", value, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態LessThan(String value) {
            addCriterion("載具歸戶狀態 <", value, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態LessThanOrEqualTo(String value) {
            addCriterion("載具歸戶狀態 <=", value, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態Like(String value) {
            addCriterion("載具歸戶狀態 like", value, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態NotLike(String value) {
            addCriterion("載具歸戶狀態 not like", value, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態In(List<String> values) {
            addCriterion("載具歸戶狀態 in", values, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態NotIn(List<String> values) {
            addCriterion("載具歸戶狀態 not in", values, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態Between(String value1, String value2) {
            addCriterion("載具歸戶狀態 between", value1, value2, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and載具歸戶狀態NotBetween(String value1, String value2) {
            addCriterion("載具歸戶狀態 not between", value1, value2, "載具歸戶狀態");
            return (Criteria) this;
        }

        public Criteria and公司驗證IsNull() {
            addCriterion("公司驗證 is null");
            return (Criteria) this;
        }

        public Criteria and公司驗證IsNotNull() {
            addCriterion("公司驗證 is not null");
            return (Criteria) this;
        }

        public Criteria and公司驗證EqualTo(Integer value) {
            addCriterion("公司驗證 =", value, "公司驗證");
            return (Criteria) this;
        }

        public Criteria and公司驗證NotEqualTo(Integer value) {
            addCriterion("公司驗證 <>", value, "公司驗證");
            return (Criteria) this;
        }

        public Criteria and公司驗證GreaterThan(Integer value) {
            addCriterion("公司驗證 >", value, "公司驗證");
            return (Criteria) this;
        }

        public Criteria and公司驗證GreaterThanOrEqualTo(Integer value) {
            addCriterion("公司驗證 >=", value, "公司驗證");
            return (Criteria) this;
        }

        public Criteria and公司驗證LessThan(Integer value) {
            addCriterion("公司驗證 <", value, "公司驗證");
            return (Criteria) this;
        }

        public Criteria and公司驗證LessThanOrEqualTo(Integer value) {
            addCriterion("公司驗證 <=", value, "公司驗證");
            return (Criteria) this;
        }

        public Criteria and公司驗證In(List<Integer> values) {
            addCriterion("公司驗證 in", values, "公司驗證");
            return (Criteria) this;
        }

        public Criteria and公司驗證NotIn(List<Integer> values) {
            addCriterion("公司驗證 not in", values, "公司驗證");
            return (Criteria) this;
        }

        public Criteria and公司驗證Between(Integer value1, Integer value2) {
            addCriterion("公司驗證 between", value1, value2, "公司驗證");
            return (Criteria) this;
        }

        public Criteria and公司驗證NotBetween(Integer value1, Integer value2) {
            addCriterion("公司驗證 not between", value1, value2, "公司驗證");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間IsNull() {
            addCriterion("公司驗證時間 is null");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間IsNotNull() {
            addCriterion("公司驗證時間 is not null");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間EqualTo(Date value) {
            addCriterion("公司驗證時間 =", value, "公司驗證時間");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間NotEqualTo(Date value) {
            addCriterion("公司驗證時間 <>", value, "公司驗證時間");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間GreaterThan(Date value) {
            addCriterion("公司驗證時間 >", value, "公司驗證時間");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間GreaterThanOrEqualTo(Date value) {
            addCriterion("公司驗證時間 >=", value, "公司驗證時間");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間LessThan(Date value) {
            addCriterion("公司驗證時間 <", value, "公司驗證時間");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間LessThanOrEqualTo(Date value) {
            addCriterion("公司驗證時間 <=", value, "公司驗證時間");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間In(List<Date> values) {
            addCriterion("公司驗證時間 in", values, "公司驗證時間");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間NotIn(List<Date> values) {
            addCriterion("公司驗證時間 not in", values, "公司驗證時間");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間Between(Date value1, Date value2) {
            addCriterion("公司驗證時間 between", value1, value2, "公司驗證時間");
            return (Criteria) this;
        }

        public Criteria and公司驗證時間NotBetween(Date value1, Date value2) {
            addCriterion("公司驗證時間 not between", value1, value2, "公司驗證時間");
            return (Criteria) this;
        }

        public Criteria and驗證IsNull() {
            addCriterion("驗證 is null");
            return (Criteria) this;
        }

        public Criteria and驗證IsNotNull() {
            addCriterion("驗證 is not null");
            return (Criteria) this;
        }

        public Criteria and驗證EqualTo(Boolean value) {
            addCriterion("驗證 =", value, "驗證");
            return (Criteria) this;
        }

        public Criteria and驗證NotEqualTo(Boolean value) {
            addCriterion("驗證 <>", value, "驗證");
            return (Criteria) this;
        }

        public Criteria and驗證GreaterThan(Boolean value) {
            addCriterion("驗證 >", value, "驗證");
            return (Criteria) this;
        }

        public Criteria and驗證GreaterThanOrEqualTo(Boolean value) {
            addCriterion("驗證 >=", value, "驗證");
            return (Criteria) this;
        }

        public Criteria and驗證LessThan(Boolean value) {
            addCriterion("驗證 <", value, "驗證");
            return (Criteria) this;
        }

        public Criteria and驗證LessThanOrEqualTo(Boolean value) {
            addCriterion("驗證 <=", value, "驗證");
            return (Criteria) this;
        }

        public Criteria and驗證In(List<Boolean> values) {
            addCriterion("驗證 in", values, "驗證");
            return (Criteria) this;
        }

        public Criteria and驗證NotIn(List<Boolean> values) {
            addCriterion("驗證 not in", values, "驗證");
            return (Criteria) this;
        }

        public Criteria and驗證Between(Boolean value1, Boolean value2) {
            addCriterion("驗證 between", value1, value2, "驗證");
            return (Criteria) this;
        }

        public Criteria and驗證NotBetween(Boolean value1, Boolean value2) {
            addCriterion("驗證 not between", value1, value2, "驗證");
            return (Criteria) this;
        }

        public Criteria and驗證時間IsNull() {
            addCriterion("驗證時間 is null");
            return (Criteria) this;
        }

        public Criteria and驗證時間IsNotNull() {
            addCriterion("驗證時間 is not null");
            return (Criteria) this;
        }

        public Criteria and驗證時間EqualTo(Date value) {
            addCriterion("驗證時間 =", value, "驗證時間");
            return (Criteria) this;
        }

        public Criteria and驗證時間NotEqualTo(Date value) {
            addCriterion("驗證時間 <>", value, "驗證時間");
            return (Criteria) this;
        }

        public Criteria and驗證時間GreaterThan(Date value) {
            addCriterion("驗證時間 >", value, "驗證時間");
            return (Criteria) this;
        }

        public Criteria and驗證時間GreaterThanOrEqualTo(Date value) {
            addCriterion("驗證時間 >=", value, "驗證時間");
            return (Criteria) this;
        }

        public Criteria and驗證時間LessThan(Date value) {
            addCriterion("驗證時間 <", value, "驗證時間");
            return (Criteria) this;
        }

        public Criteria and驗證時間LessThanOrEqualTo(Date value) {
            addCriterion("驗證時間 <=", value, "驗證時間");
            return (Criteria) this;
        }

        public Criteria and驗證時間In(List<Date> values) {
            addCriterion("驗證時間 in", values, "驗證時間");
            return (Criteria) this;
        }

        public Criteria and驗證時間NotIn(List<Date> values) {
            addCriterion("驗證時間 not in", values, "驗證時間");
            return (Criteria) this;
        }

        public Criteria and驗證時間Between(Date value1, Date value2) {
            addCriterion("驗證時間 between", value1, value2, "驗證時間");
            return (Criteria) this;
        }

        public Criteria and驗證時間NotBetween(Date value1, Date value2) {
            addCriterion("驗證時間 not between", value1, value2, "驗證時間");
            return (Criteria) this;
        }

        public Criteria and驗證姓名IsNull() {
            addCriterion("驗證姓名 is null");
            return (Criteria) this;
        }

        public Criteria and驗證姓名IsNotNull() {
            addCriterion("驗證姓名 is not null");
            return (Criteria) this;
        }

        public Criteria and驗證姓名EqualTo(String value) {
            addCriterion("驗證姓名 =", value, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證姓名NotEqualTo(String value) {
            addCriterion("驗證姓名 <>", value, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證姓名GreaterThan(String value) {
            addCriterion("驗證姓名 >", value, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證姓名GreaterThanOrEqualTo(String value) {
            addCriterion("驗證姓名 >=", value, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證姓名LessThan(String value) {
            addCriterion("驗證姓名 <", value, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證姓名LessThanOrEqualTo(String value) {
            addCriterion("驗證姓名 <=", value, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證姓名Like(String value) {
            addCriterion("驗證姓名 like", value, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證姓名NotLike(String value) {
            addCriterion("驗證姓名 not like", value, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證姓名In(List<String> values) {
            addCriterion("驗證姓名 in", values, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證姓名NotIn(List<String> values) {
            addCriterion("驗證姓名 not in", values, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證姓名Between(String value1, String value2) {
            addCriterion("驗證姓名 between", value1, value2, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證姓名NotBetween(String value1, String value2) {
            addCriterion("驗證姓名 not between", value1, value2, "驗證姓名");
            return (Criteria) this;
        }

        public Criteria and驗證資訊IsNull() {
            addCriterion("驗證資訊 is null");
            return (Criteria) this;
        }

        public Criteria and驗證資訊IsNotNull() {
            addCriterion("驗證資訊 is not null");
            return (Criteria) this;
        }

        public Criteria and驗證資訊EqualTo(String value) {
            addCriterion("驗證資訊 =", value, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and驗證資訊NotEqualTo(String value) {
            addCriterion("驗證資訊 <>", value, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and驗證資訊GreaterThan(String value) {
            addCriterion("驗證資訊 >", value, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and驗證資訊GreaterThanOrEqualTo(String value) {
            addCriterion("驗證資訊 >=", value, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and驗證資訊LessThan(String value) {
            addCriterion("驗證資訊 <", value, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and驗證資訊LessThanOrEqualTo(String value) {
            addCriterion("驗證資訊 <=", value, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and驗證資訊Like(String value) {
            addCriterion("驗證資訊 like", value, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and驗證資訊NotLike(String value) {
            addCriterion("驗證資訊 not like", value, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and驗證資訊In(List<String> values) {
            addCriterion("驗證資訊 in", values, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and驗證資訊NotIn(List<String> values) {
            addCriterion("驗證資訊 not in", values, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and驗證資訊Between(String value1, String value2) {
            addCriterion("驗證資訊 between", value1, value2, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and驗證資訊NotBetween(String value1, String value2) {
            addCriterion("驗證資訊 not between", value1, value2, "驗證資訊");
            return (Criteria) this;
        }

        public Criteria and暱稱IsNull() {
            addCriterion("暱稱 is null");
            return (Criteria) this;
        }

        public Criteria and暱稱IsNotNull() {
            addCriterion("暱稱 is not null");
            return (Criteria) this;
        }

        public Criteria and暱稱EqualTo(String value) {
            addCriterion("暱稱 =", value, "暱稱");
            return (Criteria) this;
        }

        public Criteria and暱稱NotEqualTo(String value) {
            addCriterion("暱稱 <>", value, "暱稱");
            return (Criteria) this;
        }

        public Criteria and暱稱GreaterThan(String value) {
            addCriterion("暱稱 >", value, "暱稱");
            return (Criteria) this;
        }

        public Criteria and暱稱GreaterThanOrEqualTo(String value) {
            addCriterion("暱稱 >=", value, "暱稱");
            return (Criteria) this;
        }

        public Criteria and暱稱LessThan(String value) {
            addCriterion("暱稱 <", value, "暱稱");
            return (Criteria) this;
        }

        public Criteria and暱稱LessThanOrEqualTo(String value) {
            addCriterion("暱稱 <=", value, "暱稱");
            return (Criteria) this;
        }

        public Criteria and暱稱Like(String value) {
            addCriterion("暱稱 like", value, "暱稱");
            return (Criteria) this;
        }

        public Criteria and暱稱NotLike(String value) {
            addCriterion("暱稱 not like", value, "暱稱");
            return (Criteria) this;
        }

        public Criteria and暱稱In(List<String> values) {
            addCriterion("暱稱 in", values, "暱稱");
            return (Criteria) this;
        }

        public Criteria and暱稱NotIn(List<String> values) {
            addCriterion("暱稱 not in", values, "暱稱");
            return (Criteria) this;
        }

        public Criteria and暱稱Between(String value1, String value2) {
            addCriterion("暱稱 between", value1, value2, "暱稱");
            return (Criteria) this;
        }

        public Criteria and暱稱NotBetween(String value1, String value2) {
            addCriterion("暱稱 not between", value1, value2, "暱稱");
            return (Criteria) this;
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria and鎖定IsNull() {
            addCriterion("鎖定 is null");
            return (Criteria) this;
        }

        public Criteria and鎖定IsNotNull() {
            addCriterion("鎖定 is not null");
            return (Criteria) this;
        }

        public Criteria and鎖定EqualTo(Integer value) {
            addCriterion("鎖定 =", value, "鎖定");
            return (Criteria) this;
        }

        public Criteria and鎖定NotEqualTo(Integer value) {
            addCriterion("鎖定 <>", value, "鎖定");
            return (Criteria) this;
        }

        public Criteria and鎖定GreaterThan(Integer value) {
            addCriterion("鎖定 >", value, "鎖定");
            return (Criteria) this;
        }

        public Criteria and鎖定GreaterThanOrEqualTo(Integer value) {
            addCriterion("鎖定 >=", value, "鎖定");
            return (Criteria) this;
        }

        public Criteria and鎖定LessThan(Integer value) {
            addCriterion("鎖定 <", value, "鎖定");
            return (Criteria) this;
        }

        public Criteria and鎖定LessThanOrEqualTo(Integer value) {
            addCriterion("鎖定 <=", value, "鎖定");
            return (Criteria) this;
        }

        public Criteria and鎖定In(List<Integer> values) {
            addCriterion("鎖定 in", values, "鎖定");
            return (Criteria) this;
        }

        public Criteria and鎖定NotIn(List<Integer> values) {
            addCriterion("鎖定 not in", values, "鎖定");
            return (Criteria) this;
        }

        public Criteria and鎖定Between(Integer value1, Integer value2) {
            addCriterion("鎖定 between", value1, value2, "鎖定");
            return (Criteria) this;
        }

        public Criteria and鎖定NotBetween(Integer value1, Integer value2) {
            addCriterion("鎖定 not between", value1, value2, "鎖定");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIR0客戶
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 15 14:29:23 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AIR0客戶
     *
     * @mbg.generated Tue Jul 15 14:29:23 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}